language: csharp
dotnet: 2.1.402
sudo: false  # use the new container-based Travis infrastructure
dist: trusty

before_script:
  - nvm install --lts
  - nvm use --lts
  #install yarn globally
  - npm install -g yarn

cache:
  yarn: true

script:
  - ./build.sh